ECOMMERCE/urls.py
from django.contrib import admin
from django.urls import path, include

# Para el manejo de archivos
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('sitio.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitio/urls.py
from django.urls import path
from . import views

app_name = "SITIO"
urlpatterns = [
    # REGISTRAR USUARIO
    path('registrarse/', views.register, name="register"),


    # ACERCA DE
    path('acercaDe', views.acerca_de, name="acerca_de"),
    
    # PRODUCTOS
    path('', views.producto_index, name="producto_index"),
    path('producto/agregar', views.producto_create, name="producto_create" ),
    path('producto/<int:producto_id>', views.producto_show, name="producto_show" ),
    path('producto/<int:producto_id>/editar', views.producto_edit, name="producto_edit" ),
    path('producto/<int:producto_id>/eliminar', views.producto_delete, name="producto_delete" ),
    path('producto/buscador', views.producto_search, name="producto_search"),
    path('categoria/<int:categoria_id>/productos', views.productos_por_categoria, name="productos_por_categoria"),

    # CARRITO
    path('carrito', views.carrito_index, name="carrito_index"),
    path('carrito/agregar', views.carrito_save, name="carrito_save"),
    path('carrito/clean', views.carrito_clean, name="carrito_clean"),
    path('item_carrito/<int:item_carrito_id>/eliminar', views.item_carrito_delete, name="item_carrito_delete"),

]

sitio/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Categoria(models.Model):
    descripcion = models.CharField(max_length=200, null=False)

    def __str__(self) -> str:
        return f"Id: {self.pk} | Descripcion: {self.descripcion}"


class Producto(models.Model):
    titulo = models.CharField(max_length=50, null=False)
    # Imagen
    imagen = models.FileField(upload_to='imagenes/productos/')
    descripcion = models.CharField(max_length=200, null=False)
    precio = models.DecimalField(null=False, max_digits=10, decimal_places=2)
    # FK
    categoria = models.ForeignKey(Categoria,on_delete=models.CASCADE, related_name="productos")

    def __str__(self) -> str:
        return f"Id: {self.pk} | Titulo: {self.titulo} | Imagen: {self.imagen} | Descripcion: {self.descripcion} | Precio: {self.precio} || Categoria_id: {self.categoria.id} "


class Carrito(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name="carrito")
    total = models.DecimalField(null=False, max_digits=10, decimal_places=2)

    def __str__(self) -> str:
        return f"Id: {self.pk} | Usuario_id: {self.usuario.id} | Usuario: {self.usuario.username} | Total: {self.total}"


class Carrito_item(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE) 
    carrito = models.ForeignKey(Carrito, on_delete=models.CASCADE, related_name="items")

    def __str__(self) -> str:
        return f"Id: {self.pk} | Producto: {self.producto.titulo} | Carrito_id: {self.carrito.id}"

sitio/forms.py
from django import forms
from django.db.models import fields
from .models import Producto
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

""" 
    PRODUCTO 
"""
class FormProducto(forms.ModelForm):

    class Meta:
        model = Producto
        fields = ('titulo','imagen','descripcion','precio','categoria')
        """ widgets = {
            'titulo': forms.TextInput(),
            'descripcion' : forms.Textarea(),
            'precio' : forms.NumberInput(),
            'imagen' : forms.FileField()
        } """
        """ widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Ingrese el nombre del producto...' , 'required': True}),
            'descripcion' : forms.Textarea(attrs={'class' : 'form-control', 'row' : 3, 'required': True}),
            'precio' : forms.NumberInput(attrs={'class' : 'form-control', 'placeholder':'XXXX.XX', 'required': True}),
            'imagen' : forms.FileField(attrs={'class':'form-control-file', 'id':'imagen', 'placeholder': 'Ingrese la imagen...', 'required': True})
        } """

sitio/views.py
from django.contrib.auth.models import User
from sitio.forms import FormProducto
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http.response import HttpResponse

from sitio.models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
""" 
    REGISTRO DE USUARIO
"""
def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            usuario_logeado = User.objects.last()
            #username = form.cleaned_data['username']
            messages.success(request, f"El usuario ha sido registrado exitosamente!")
            carrito = Carrito()
            carrito.usuario = usuario_logeado
            carrito.total = 0
            carrito.save()
            return redirect('SITIO:producto_index')
        else:
            messages.success(request, "No se pudo registrar el usuario, vuelva a intenarlo!")

    return render(request, 'sitio/register.html')

""" 
    PRODUCTOS
"""
def producto_index(request):
    productos = Producto.objects.all().order_by("-id")
    
    return render(request, "sitio/producto/index.html", {
        'categorias' : Categoria.objects.all(),
        'productos_top3' : productos[:3],
        'productos' : productos[3:10]
    })

# PARA ADMINS/MODERADORES
def producto_create(request):
    categorias = Categoria.objects.all()
    if request.method == "POST":
        categoria_del_producto = Categoria.objects.get(id=request.POST["categoria"])
        form = FormProducto(request.POST, request.FILES, instance=Producto(imagen=request.FILES['imagen'], categoria=categoria_del_producto))   
        if form.is_valid():
            form.save()
            return redirect("SITIO:producto_index")
            #return HttpResponse('Los campos fueron validados y aceptados!!! ' + str(categoria_del_producto))
        else:
            return render(request, 'sitio/producto/create.html', {
                'categorias' : categorias,
                'error_message' : 'Ingreso un campo incorrecto, vuelva a intentar'
            })
    else:
        return render(request, 'sitio/producto/create.html', {
            'categorias' : categorias
        })

def producto_show(request, producto_id):
    producto =  get_object_or_404(Producto, id=producto_id)

    return render(request, 'sitio/producto/show.html',{
        'categorias' : Categoria.objects.all(),
        'producto' : producto
    })

def producto_edit(request, producto_id):
    categorias = Categoria.objects.all()
    producto = Producto.objects.get(id=producto_id)

    if request.method == "POST":
        categoria_del_producto = Categoria.objects.get(id=request.POST["categoria"])
        form = FormProducto(request.POST, request.FILES, instance=Producto(imagen=request.FILES['imagen'], categoria=categoria_del_producto))   
        if form.is_valid():
            producto.titulo = request.POST['titulo']
            producto.categoria = categoria_del_producto
            producto.descripcion = request.POST['descripcion']
            producto.imagen = request.FILES['imagen']
            producto.precio = request.POST['precio']
            producto.save()
            return redirect("SITIO:producto_index")
        else:
            return render(request, 'sitio/producto/edit.html', {
                'categorias' : categorias,
                'error_message' : 'Ingreso un campo incorrecto, vuelva a intentar'
            })
    else:
        return render(request, 'sitio/producto/edit.html',{
            'categorias' : categorias,
            'producto' : producto
        })

def producto_delete(request, producto_id):
    producto = Producto.objects.get(id=producto_id)
    producto.delete()
    return redirect('SITIO:producto_index')
    #return HttpResponse(f'Eliminar producto_id: {producto.id}')

def producto_search(request):
    texto_de_busqueda = request.GET["texto"]
    productosPorTitulo = Producto.objects.filter(titulo__icontains = texto_de_busqueda).all()
    productosPorDescripcion = Producto.objects.filter(descripcion__icontains = texto_de_busqueda).all()
    productos = productosPorTitulo | productosPorDescripcion
    return render(request, 'sitio/producto/search.html',
    {
        'categorias' : Categoria.objects.all(),
        'productos' : productos,
        'texto_buscado' : texto_de_busqueda,
        'titulo_seccion' : 'Productos que contienen',
        'sin_productos' : 'No hay producto de la categoria ' + texto_de_busqueda
    })

def productos_por_categoria(request, categoria_id):
    
    #categoria = Categoria.objects.get(id=categoria_id)
    categoria = get_object_or_404(Categoria, id = categoria_id)
    productos = categoria.productos.all()
    return render(request, 'sitio/producto/search.html',
    {
        'categorias' : Categoria.objects.all(),
        'productos' : productos,
        'categoria' : categoria.descripcion,
        'titulo_seccion' : 'Productos de la categoria',
        'sin_productos' : 'No hay producto de la categoria ' + categoria.descripcion
    })

""" 
    CARRITO
"""
def carrito_index(request):
    categorias = Categoria.objects.all()
    usuario_logeado = User.objects.get(username=request.user)
    productos = Carrito.objects.get(usuario=usuario_logeado.id).items.all()

    carrito = Carrito.objects.get(usuario=usuario_logeado.id)
    nuevo_precio_Carrito = 0
    for item in carrito.items.all():
        nuevo_precio_Carrito += item.producto.precio
    carrito.total = nuevo_precio_Carrito
    carrito.save()

    return render(request, 'sitio/carrito/index.html', {
        'categorias' : categorias,
        'usuario' : usuario_logeado,
        'items_carrito' : productos
    })

def carrito_save(request):
    #tieneCarrito = Carrito.objects.filter(usuario=8).count()
    # Devuelve un 404 si no encuentra el carrito
    #arrito = get_object_or_404(Carrito, usuario=usuario_logeado.id)

    if request.method == 'POST':
        producto = Producto.objects.get(id=request.POST['producto_id'])
        usuario_logeado = User.objects.get(username=request.user)

        # Agrego producto al carrito
        carrito = Carrito.objects.get(usuario=usuario_logeado.id)
        item_carrito = Carrito_item()
        item_carrito.carrito = carrito
        item_carrito.producto = producto
        item_carrito.save()

        # Sumo el precio del producto al carrito
        carrito.total = producto.precio + carrito.total
        carrito.save()
        messages.success(request, f"El producto {producto.titulo} fue agregado al carrito")
        #return HttpResponse(f"{usuario_logeado.id} | ITEM_CARRITO: {item_carrito} | CARRITO: {carrito}")
        return redirect("SITIO:producto_index")

    else:
        return redirect("SITIO:producto_index")

def carrito_clean(request):
    usuario_logeado = User.objects.get(username=request.user)
    carrito = Carrito.objects.get(usuario=usuario_logeado.id)
    carrito.items.all().delete()
    carrito.total = 0
    carrito.save()
    #return HttpResponse(f'Carrito: id({carrito.id}) ${carrito.total} | Usuario: id({usuario_logeado.id}) {usuario_logeado.username} | items_carrito: {carrito.items.all().count()}')
    return redirect('SITIO:carrito_index')

def item_carrito_delete(request, item_carrito_id):
    item_carrito = Carrito_item.objects.get(id=item_carrito_id)
    carrito = item_carrito.carrito
    
    # Vuelvo a calcular el precio del carrito
    nuevo_precio_Carrito = 0 - item_carrito.producto.precio
    for item in carrito.items.all():
        nuevo_precio_Carrito += item.producto.precio

    # Realizo los cambios en la base de datos
    carrito.total = nuevo_precio_Carrito
    item_carrito.delete()
    carrito.save()
    return redirect("SITIO:carrito_index")
    #return HttpResponse(f'Carrito_id: {carrito.id} Total: {carrito.total} | Item_carrito: {item_carrito} | Precio: {precio_item}')

"""
    PAGINAS
"""
def acerca_de(request):
    return render(request, 'sitio/paginas/acerca_de.html',{
        'categorias' : Categoria.objects.all(),
    })

sitio/templates/sitio/layout.html
{% load static %}

<!doctype html>
<html lang="es">

<head>
    <title>Local |Alex la Hera </title>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/deecb3ce02.js" crossorigin="anonymous"></script>

    <!-- Mis estilos CSS -->
    <link rel="stylesheet" href="{% static 'sitio/style.css' %}">
</head>

<body>

    <!-- HEADER -->
    <header class="bg-warning">
        <div class="container d-flex py-2">
            
            <a class="m-0 p-0 text-dark nav-logo" href="/">
                Alex la Hera
            </a>
    
            <div class="ml-auto d-flex">
                {% if user.is_authenticated %}
                <!-- Estas conectado como: { { user.get_username } }  -->
                <a role="button" class="btn btn-secondary mr-3" title="Salir" href="{% url 'logout'%}?next=/">
                    <i class="fas fa-sign-out-alt"></i>
                </a>
                {% else %}
                <a role="button" class="btn btn-primary mr-3" href="{% url 'login'%}?next={{request.path}}">
                    Ingresar
                </a>
                <a role="button" class="btn btn-secondary mr-3" href="{% url 'SITIO:register' %}">
                    Registrarse
                </a>
                {% endif %}
                
                {% if user.is_superuser or not user.is_authenticated %}
                    <button role="button" class="btn btn-success mr-3" disabled>
                        <i class="fas fa-shopping-cart"></i>
                    </button>
                {% else %}
                    <a role="button" class="btn btn-success mr-3" href="{% url 'SITIO:carrito_index' %}">
                        <i class="fas fa-shopping-cart"></i>
                    </a>
                {% endif %}
            </div>

        </div>
    </header>

    <!-- NAV -->
    <nav class="navbar navbar-expand-md navbar-light border">
        <div class="container py-2 ">

            <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse"
                data-target="#collapsibleNavId" aria-controls="collapsibleNavId" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="collapsibleNavId">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">Inicio</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">Categorias</a>
                        <div class="dropdown-menu" aria-labelledby="dropdownId">

                            {% for categoria in categorias %}
                                <a class="dropdown-item" href="{% url 'SITIO:productos_por_categoria' categoria.id %}">{{ categoria.descripcion.capitalize }}</a>
                            {% endfor %}

                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'SITIO:acerca_de' %}">Acerca de</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="mailto:pipevaldes05@gmail.com">Contacto</a>
                    </li>

                    <!-- PARA ADMINS/MODERADORES -->
                    {% if user.is_superuser %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'SITIO:producto_create' %}">Agregar producto</a>
                        </li>
                    {% endif %}

                </ul>
                <form action="{% url 'SITIO:producto_search' %}" method="GET" class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" name="texto" type="text" placeholder="Buscar producto...">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscador</button>
                </form>
            </div>
        </div>
    </nav>

    <!-- MAIN -->
    <main class="container my-3">

        {% block content %}
        {% endblock %}

    </main>

    <!-- FOOTER -->
    <footer class="bg-light p-3 border-top">
        <div class="container">
            <p class="p-0 m-0 mb-2 logo-empresa-footer">Donde Alex la Hera | Derechos reservados &reg;</p>
            <p class="p-0 m-0 mx-5 text-secondary">Desarrollado por Byte eat</p>
            <!-- <p class="p-0 m-0"> </p> -->
        </div>
    </footer>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

sitio/templates/sitio/register.html
{% extends 'registration/layout.html' %}

{% block content %}
<div class="row">

    <!-- MENSAJE -->
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-danger alert-dismissible fade show col-12" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
                <strong>{{message}}</strong> 
            </div>
        {% endfor %}
    {% endif %}

    <!-- TITULO -->
    <div class="col-12 mb-3">
        <h1 class="text-uppercase text-center display-4 title-form-register" >REGISTRARSE</h1>
    </div>

    <!-- FORMULARIO -->
    <form action="" method="POST" class="col-md-8 mx-auto">
        
        {% csrf_token %}

        <!-- EMAIL -->
        <div class="form-group row ">
            <label for="email" class="col-4 col-form-label text-right">Email:</label>
            <div class="col-8 col-lg-6">
                <input type="text" class="form-control" id="email" name="email" aria-describedat="emailHelp">
                <small id="emailHelp" class="text-muted">Debe contener un @ y .com</small>
            </div>
        </div>

        <!-- USUARIO -->
        <div class="form-group row ">
            <label for="usuario" class="col-4 col-form-label text-right">Usuario:</label>
            <div class="col-8 col-lg-6">
                <input type="text" class="form-control" id="usuario" name="username" aria-describedby="usernameHelp">
                <small id="usernameHelp" class="text-muted">150 carácteres como máximo. Únicamente letras, dígitos y @/./+/-/_</small>
            </div>
        </div>

        <!-- PASSWORD -->
        <div class="form-group row ">
            <label for="password" class="col-4 col-form-label text-right">Password:</label>
            <div class="col-8 col-lg-6">
                <input type="password" class="form-control" id="password" name="password1" aria-describedby="password1Help">
                <small id="password1Help" class="text-muted">
                    No puede asemejarse tanto a su otra información personal. <br>
                    Debe contener al menos 8 caracteres. <br>
                    No puede ser una clave utilizada comúnmente. <br>
                    No puede ser completamente numérica.
                </small>
            </div>
        </div>

        <!-- PASSWORD REPEAT -->
        <div class="form-group row ">
            <label for="passwordRepeat" class="col-4 col-form-label text-right">Repetir Password:</label>
            <div class="col-8 col-lg-6">
                <input type="password" class="form-control" id="passwordRepeat" name="password2" aria-describedby="password2Help">
                <small id="password2Help" class="text-muted">Repita la password anterior</small>
            </div>
        </div>
        
        <!-- BOTONES -->
        <div class="form-group row mt-4">
            <div class="col-4 col-md-4 col-lg-3 offset-4 offset-lg-4">    
                <button type="submit" class="btn btn-success btn-block text-uppercase">Registrarse</button>
            </div>
        </div>
        
    </form>

</div>
{% endblock %}