ECOMMERCE/urls.py
from django.contrib import admin
from django.urls import path, include

# Para el manejo de archivos
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('sitio.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitio/urls.py
from django.urls import path
from . import views

app_name = "SITIO"
urlpatterns = [
    # REGISTRAR USUARIO
    path('registrarse/', views.register, name="register"),


    # ACERCA DE
    path('acercaDe', views.acerca_de, name="acerca_de"),
    
    # PRODUCTOS
    path('', views.producto_index, name="producto_index"),
    path('producto/agregar', views.producto_create, name="producto_create" ),
    path('producto/<int:producto_id>', views.producto_show, name="producto_show" ),
    path('producto/<int:producto_id>/editar', views.producto_edit, name="producto_edit" ),
    path('producto/<int:producto_id>/eliminar', views.producto_delete, name="producto_delete" ),
    path('producto/buscador', views.producto_search, name="producto_search"),
    path('categoria/<int:categoria_id>/productos', views.productos_por_categoria, name="productos_por_categoria"),

    # CARRITO
    path('carrito', views.carrito_index, name="carrito_index"),
    path('carrito/agregar', views.carrito_save, name="carrito_save"),
    path('carrito/clean', views.carrito_clean, name="carrito_clean"),
    path('item_carrito/<int:item_carrito_id>/eliminar', views.item_carrito_delete, name="item_carrito_delete"),

]

sitio/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Categoria(models.Model):
    descripcion = models.CharField(max_length=200, null=False)

    def __str__(self) -> str:
        return f"Id: {self.pk} | Descripcion: {self.descripcion}"


class Producto(models.Model):
    titulo = models.CharField(max_length=50, null=False)
    # Imagen
    imagen = models.FileField(upload_to='imagenes/productos/')
    descripcion = models.CharField(max_length=200, null=False)
    precio = models.DecimalField(null=False, max_digits=10, decimal_places=2)
    # FK
    categoria = models.ForeignKey(Categoria,on_delete=models.CASCADE, related_name="productos")

    def __str__(self) -> str:
        return f"Id: {self.pk} | Titulo: {self.titulo} | Imagen: {self.imagen} | Descripcion: {self.descripcion} | Precio: {self.precio} || Categoria_id: {self.categoria.id} "


class Carrito(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name="carrito")
    total = models.DecimalField(null=False, max_digits=10, decimal_places=2)

    def __str__(self) -> str:
        return f"Id: {self.pk} | Usuario_id: {self.usuario.id} | Usuario: {self.usuario.username} | Total: {self.total}"


class Carrito_item(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE) 
    carrito = models.ForeignKey(Carrito, on_delete=models.CASCADE, related_name="items")

    def __str__(self) -> str:
        return f"Id: {self.pk} | Producto: {self.producto.titulo} | Carrito_id: {self.carrito.id}"

sitio/forms.py
from django import forms
from django.db.models import fields
from .models import Producto
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

""" 
    PRODUCTO 
"""
class FormProducto(forms.ModelForm):

    class Meta:
        model = Producto
        fields = ('titulo','imagen','descripcion','precio','categoria')
        """ widgets = {
            'titulo': forms.TextInput(),
            'descripcion' : forms.Textarea(),
            'precio' : forms.NumberInput(),
            'imagen' : forms.FileField()
        } """
        """ widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Ingrese el nombre del producto...' , 'required': True}),
            'descripcion' : forms.Textarea(attrs={'class' : 'form-control', 'row' : 3, 'required': True}),
            'precio' : forms.NumberInput(attrs={'class' : 'form-control', 'placeholder':'XXXX.XX', 'required': True}),
            'imagen' : forms.FileField(attrs={'class':'form-control-file', 'id':'imagen', 'placeholder': 'Ingrese la imagen...', 'required': True})
        } """

sitio/views.py
from django.contrib.auth.models import User
from sitio.forms import FormProducto
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http.response import HttpResponse

from sitio.models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
""" 
    REGISTRO DE USUARIO
"""
def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            usuario_logeado = User.objects.last()
            #username = form.cleaned_data['username']
            messages.success(request, f"El usuario ha sido registrado exitosamente!")
            carrito = Carrito()
            carrito.usuario = usuario_logeado
            carrito.total = 0
            carrito.save()
            return redirect('SITIO:producto_index')
        else:
            messages.success(request, "No se pudo registrar el usuario, vuelva a intenarlo!")

    return render(request, 'sitio/register.html')

""" 
    PRODUCTOS
"""
def producto_index(request):
    productos = Producto.objects.all().order_by("-id")
    
    return render(request, "sitio/producto/index.html", {
        'categorias' : Categoria.objects.all(),
        'productos_top3' : productos[:3],
        'productos' : productos[3:10]
    })

# PARA ADMINS/MODERADORES
def producto_create(request):
    categorias = Categoria.objects.all()
    if request.method == "POST":
        categoria_del_producto = Categoria.objects.get(id=request.POST["categoria"])
        form = FormProducto(request.POST, request.FILES, instance=Producto(imagen=request.FILES['imagen'], categoria=categoria_del_producto))   
        if form.is_valid():
            form.save()
            return redirect("SITIO:producto_index")
            #return HttpResponse('Los campos fueron validados y aceptados!!! ' + str(categoria_del_producto))
        else:
            return render(request, 'sitio/producto/create.html', {
                'categorias' : categorias,
                'error_message' : 'Ingreso un campo incorrecto, vuelva a intentar'
            })
    else:
        return render(request, 'sitio/producto/create.html', {
            'categorias' : categorias
        })

def producto_show(request, producto_id):
    producto =  get_object_or_404(Producto, id=producto_id)

    return render(request, 'sitio/producto/show.html',{
        'categorias' : Categoria.objects.all(),
        'producto' : producto
    })

def producto_edit(request, producto_id):
    categorias = Categoria.objects.all()
    producto = Producto.objects.get(id=producto_id)

    if request.method == "POST":
        categoria_del_producto = Categoria.objects.get(id=request.POST["categoria"])
        form = FormProducto(request.POST, request.FILES, instance=Producto(imagen=request.FILES['imagen'], categoria=categoria_del_producto))   
        if form.is_valid():
            producto.titulo = request.POST['titulo']
            producto.categoria = categoria_del_producto
            producto.descripcion = request.POST['descripcion']
            producto.imagen = request.FILES['imagen']
            producto.precio = request.POST['precio']
            producto.save()
            return redirect("SITIO:producto_index")
        else:
            return render(request, 'sitio/producto/edit.html', {
                'categorias' : categorias,
                'error_message' : 'Ingreso un campo incorrecto, vuelva a intentar'
            })
    else:
        return render(request, 'sitio/producto/edit.html',{
            'categorias' : categorias,
            'producto' : producto
        })

def producto_delete(request, producto_id):
    producto = Producto.objects.get(id=producto_id)
    producto.delete()
    return redirect('SITIO:producto_index')
    #return HttpResponse(f'Eliminar producto_id: {producto.id}')

def producto_search(request):
    texto_de_busqueda = request.GET["texto"]
    productosPorTitulo = Producto.objects.filter(titulo__icontains = texto_de_busqueda).all()
    productosPorDescripcion = Producto.objects.filter(descripcion__icontains = texto_de_busqueda).all()
    productos = productosPorTitulo | productosPorDescripcion
    return render(request, 'sitio/producto/search.html',
    {
        'categorias' : Categoria.objects.all(),
        'productos' : productos,
        'texto_buscado' : texto_de_busqueda,
        'titulo_seccion' : 'Productos que contienen',
        'sin_productos' : 'No hay producto de la categoria ' + texto_de_busqueda
    })

def productos_por_categoria(request, categoria_id):
    
    #categoria = Categoria.objects.get(id=categoria_id)
    categoria = get_object_or_404(Categoria, id = categoria_id)
    productos = categoria.productos.all()
    return render(request, 'sitio/producto/search.html',
    {
        'categorias' : Categoria.objects.all(),
        'productos' : productos,
        'categoria' : categoria.descripcion,
        'titulo_seccion' : 'Productos de la categoria',
        'sin_productos' : 'No hay producto de la categoria ' + categoria.descripcion
    })

""" 
    CARRITO
"""
def carrito_index(request):
    categorias = Categoria.objects.all()
    usuario_logeado = User.objects.get(username=request.user)
    productos = Carrito.objects.get(usuario=usuario_logeado.id).items.all()

    carrito = Carrito.objects.get(usuario=usuario_logeado.id)
    nuevo_precio_Carrito = 0
    for item in carrito.items.all():
        nuevo_precio_Carrito += item.producto.precio
    carrito.total = nuevo_precio_Carrito
    carrito.save()

    return render(request, 'sitio/carrito/index.html', {
        'categorias' : categorias,
        'usuario' : usuario_logeado,
        'items_carrito' : productos
    })

def carrito_save(request):
    #tieneCarrito = Carrito.objects.filter(usuario=8).count()
    # Devuelve un 404 si no encuentra el carrito
    #arrito = get_object_or_404(Carrito, usuario=usuario_logeado.id)

    if request.method == 'POST':
        producto = Producto.objects.get(id=request.POST['producto_id'])
        usuario_logeado = User.objects.get(username=request.user)

        # Agrego producto al carrito
        carrito = Carrito.objects.get(usuario=usuario_logeado.id)
        item_carrito = Carrito_item()
        item_carrito.carrito = carrito
        item_carrito.producto = producto
        item_carrito.save()

        # Sumo el precio del producto al carrito
        carrito.total = producto.precio + carrito.total
        carrito.save()
        messages.success(request, f"El producto {producto.titulo} fue agregado al carrito")
        #return HttpResponse(f"{usuario_logeado.id} | ITEM_CARRITO: {item_carrito} | CARRITO: {carrito}")
        return redirect("SITIO:producto_index")

    else:
        return redirect("SITIO:producto_index")

def carrito_clean(request):
    usuario_logeado = User.objects.get(username=request.user)
    carrito = Carrito.objects.get(usuario=usuario_logeado.id)
    carrito.items.all().delete()
    carrito.total = 0
    carrito.save()
    #return HttpResponse(f'Carrito: id({carrito.id}) ${carrito.total} | Usuario: id({usuario_logeado.id}) {usuario_logeado.username} | items_carrito: {carrito.items.all().count()}')
    return redirect('SITIO:carrito_index')

def item_carrito_delete(request, item_carrito_id):
    item_carrito = Carrito_item.objects.get(id=item_carrito_id)
    carrito = item_carrito.carrito
    
    # Vuelvo a calcular el precio del carrito
    nuevo_precio_Carrito = 0 - item_carrito.producto.precio
    for item in carrito.items.all():
        nuevo_precio_Carrito += item.producto.precio

    # Realizo los cambios en la base de datos
    carrito.total = nuevo_precio_Carrito
    item_carrito.delete()
    carrito.save()
    return redirect("SITIO:carrito_index")
    #return HttpResponse(f'Carrito_id: {carrito.id} Total: {carrito.total} | Item_carrito: {item_carrito} | Precio: {precio_item}')

"""
    PAGINAS
"""
def acerca_de(request):
    return render(request, 'sitio/paginas/acerca_de.html',{
        'categorias' : Categoria.objects.all(),
    })

sitio/templates/sitio/producto/create.html
{% extends 'sitio/layout.html' %}

{% block content %}
<section class="row mt-5 container mx-auto">

    <!-- MENSAGE DE ERROR -->
    {% if error_message %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>{{ error_message }}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}

    <!-- TITULO -->
    <div class="col-12">
        <h2 class="display-4 text-center mb-5">Agregar producto</h2>
    </div>

    <!-- FORMULARIO -->
    <form action="{% url 'SITIO:producto_create' %}" method="post" enctype="multipart/form-data" class="w-100 col-12">

        {% csrf_token %}

        <!-- NOMBRE PRODUCTO -->
        <div class="col-12 p-0 form-group">
            <input class="form-control" type="text" name="titulo" placeholder="Ingrese el nombre del producto..." required>
        </div>

        <div class="row container mx-auto p-0 pt-3">

            <!-- IMAGEN -->
            <div class="col-md-6 p-0 m-0">
                <div class="form-group">
                    <label for="imagen">IMAGEN</label>
                    <input type="file" class="form-control-file" name="imagen" id="imagen"
                        placeholder="Ingrese la imagen..." required>
                </div>
            </div>

            <div class="col-md-6 p-0 m-0 row">

                <!-- CATEGORIA -->
                <div class="col-12 p-0 form-group">
                    <select class="custom-select" name="categoria" required>
                        <option value="" selected>-- Seleccione la categoria --</option>
                        {% for categoria in categorias %}
                            <option value="{{ categoria.id }}">{{ categoria.descripcion }}</option>
                        {% endfor %}
                    </select>
                </div>

                <!-- DESCRIPCION -->
                <div class="col-12 p-0 form-group mb-3">
                    <textarea class="form-control" name="descripcion" rows="3" required></textarea>
                </div>

                <div class="col-12 ">
                    <div class="row justify-content-between align-items-center">
                        <!-- PRECIO -->
                        <div class="col-auto m-0 p-0">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <div class="input-group-text">Precio: $</div>
                                </div>
                                <input type="number" class="form-control" name="precio" placeholder="XXXX.XX" required>
                            </div>
                        </div>

                        <!-- BOTON -->
                        <div class="form-group col-md-4 col-lg-3 m-0 p-0 mt-2 mt-lg-0">
                            <button type="submit" class="btn btn-success btn-block">Agregar</button>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </form>

</section>
{% endblock %}

sitio/templates/sitio/producto/edit.html
{% extends 'sitio/layout.html' %}

{% block content %}
<section class="row my-5 container mx-auto">

    <!-- MENSAGE DE ERROR -->
    {% if error_message %}
        <div class="alert alert-danger alert-dismissible fade show col-12" role="alert">
            <strong>{{ error_message }}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}
    {% if okey_message %}
        <div class="alert alert-danger alert-dismissible fade show col-12" role="alert">
            <strong>{{ okey_message }}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}

    <!-- TITULO -->
    <div class="col-12">
        <h2 class="display-4 text-center mb-5">Editar producto</h2>
    </div>

    <!-- FORMULARIO -->
    <form action="" method="post" enctype="multipart/form-data" class="w-100 col-12">

        {% csrf_token %}

        <!-- NOMBRE PRODUCTO -->
        <div class="col-12 p-0 form-group">
            <input class="form-control" type="text" name="titulo" placeholder="Ingrese el nombre del producto..." value="{{producto.titulo.title}}" required>
        </div>

        <div class="row container mx-auto p-0 pt-3">

            <!-- IMAGEN -->
            <div class="col-md-6 p-0 m-0">
                <div class="form-group">
                    <label for="imagen">IMAGEN</label>
                    <input type="file" class="form-control-file" name="imagen" id="imagen"
                        placeholder="Ingrese la imagen..." required>
                </div>
            </div>

            <div class="col-md-6 p-0 m-0 row">

                <!-- CATEGORIA -->
                <div class="col-12 p-0 form-group">
                    <select class="custom-select" name="categoria" required>
                        <option value="" selected>-- Seleccione la categoria --</option>
                        {% for categoria in categorias %}
                            <option value="{{ categoria.id }}">{{ categoria.descripcion }}</option>
                        {% endfor %}
                    </select>
                </div>

                <!-- DESCRIPCION -->
                <div class="col-12 p-0 form-group mb-3">
                    <textarea class="form-control" name="descripcion" rows="3" required>{{producto.descripcion.capitalize}}</textarea>
                </div>

                <div class="col-12 ">
                    <div class="row justify-content-between align-items-center">
                        <!-- PRECIO -->
                        <div class="col-auto m-0 p-0">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <div class="input-group-text">Precio: $</div>
                                </div>
                                <input type="number" class="form-control" name="precio" placeholder="XXXX.XX" value="{{ producto.precio|floatformat }}" required>
                            </div>
                        </div>

                        <!-- BOTON -->
                        <div class="form-group col-md-4 col-lg-3 m-0 p-0 mt-2 mt-lg-0">
                            <button type="submit" class="btn btn-success btn-block">Editar</button>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </form>

</section>
{% endblock %}

sitio/templates/sitio/producto/index.html
{% extends "sitio/layout.html" %}

{% block content %}

    <!-- ULTIMOS 3 PRODUCTOS -->
    <section class="row">

        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-warning alert-dismissible fade show col-12" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                    <strong>{{message}}</strong> 
                </div>
            {% endfor %}
        {% endif %}

        <!-- Titulo -->
        <div class="col-12 mb-4 ">
            <h1 class="display-4 text-center">Ultimos Productos</h1>
        </div>

        <!-- PRODUCTOS -->
        {% for producto in productos_top3 %}
            <div class="col-12 col-sm-6 col-md-4 mb-3">
                <div class="card card-img-3-producto-home">
                    <div class=" h-100 ">
                        <!-- src="https://picsum.photos/200/200?random={{ forloop.counter }}" -->
                        <img 
                        class="card-img-top mx-auto"
                        src="{{MEDIA_URL}}{{producto.imagen.url}}"
                        alt="{{producto.titulo}}"
                        >
                    </div>
                    <div class="card-body card-body-3-productos-home">
                        <h4 class="card-title text-truncate">{{ producto.titulo.title.title|truncatechars:25 }}</h4>
                        <p class="card-text ">{{ producto.descripcion.capitalize|truncatechars:70 }}</p>
                        <a href="{% url 'SITIO:producto_show' producto.id %}" class="btn btn-success btn-block">Ver</a>
                        
                        {% if user.is_superuser %}
                            <a href="{% url 'SITIO:producto_edit' producto.id %}" class="btn btn-outline-secondary btn-block">Editar</a>
                            <a href="{% url 'SITIO:producto_delete' producto.id %}" class="btn btn-outline-danger btn-block">Eliminar</a>
                        {% endif %}

                    </div>
                </div>
            </div>
        {% endfor %}
    </section>


    <!-- MAS PRODUCTOS -->
    <section class="row mt-4">
        <!-- Titulo -->
        <div class="col-12 mb-4">
            <h2 class="display-4 text-center">Mas Productos</h2>
        </div>

        <!-- Otros productos -->
        <div class="row row-cols-1 row-cols-md-3 container justify-content-center">
            {% for producto in productos %}
                <div class="col-6 col-md-3 mb-4">
                    <div class="card h-100 card-img-producto-home">
                        <!-- src="https://picsum.photos/200/200?random={{ forloop.counter }}" -->
                        <img 
                        class="card-img-top mx-auto"
                        
                        src="{{MEDIA_URL}}{{producto.imagen.url}}"
                        alt="ultimo producto 1"
                        >
                        <div class="card-body text-center">
                            <h4 class="card-title">{{ producto.titulo.title|truncatechars:28 }}</h4>
                            <p class="card-text ">{{ producto.descripcion.capitalize|truncatechars:50 }}</p>
                            <a href="{% url 'SITIO:producto_show' producto.id %}" class="btn btn-success btn-block">Ver</a>

                            {% if user.is_superuser %}
                                <a href="{% url 'SITIO:producto_edit' producto.id %}" class="btn btn-outline-secondary btn-block">Editar</a>
                                <a href="{% url 'SITIO:producto_delete' producto.id %}" class="btn btn-outline-danger btn-block">Eliminar</a>
                            {% endif %}

                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </section>

{% endblock %}

sitio/templates/sitio/producto/resultado_busqueda.html
{% extends "sitio/layout.html" %}

{% block content %}
<section class="row mt-5">

    <!-- Titulo -->
    <div class="col-12 mb-4">
        {% if categoria %}
        <h2 class="display-4 text-center text-capitalize ">
            {{ titulo_seccion }}
            <strong>
                "{{ categoria }}"
            </strong>
        </h2>
        {% endif %}
        <!-- <h2 class="display-4 text-center text-capitalize ">Listado de productos "Input busqueda"</h2>
        <h2 class="display-4 text-center text-capitalize ">O Listado de productos por categoria</h2> -->
    </div>

    <!-- Productos -->
    <div class="row row-cols-1 row-cols-md-3 container justify-content-center">

        {% for producto in productos %}
            <div class="col-6 col-md-4 col-lg-3 mb-4">
                <div class="card h-100 card-img-producto-home">
                    <img 
                    class="card-img-top mx-auto"
                    src="https://picsum.photos/200/200?random={{ forloop.counter }}"
                    alt="ultimo producto 1"
                    >
                    <div class="card-body text-center">
                        <h4 class="card-title">{{ producto.titulo.title }}</h4>
                        <p class="card-text ">{{ producto.descripcion.capitalize|truncatechars:50 }}</p>
                        <a href="{% url 'SITIO:producto_show' producto.id %}" class="btn btn-success btn-block">Ver</a>
                    </div>
                </div>
            </div>
        {% empty %}
        <h2 class="col-12 display-4 text-center mt-5" style="font-size: 2em; height: 30vh;">No hay productos que
            coincidan</h2>
        {% endfor %}

    </div>

</section>
{% endblock %}

sitio/templates/sitio/producto/search.html
{% extends "sitio/layout.html" %}

{% block content %}
<section class="row mt-5">

    <!-- Titulo -->
    <div class="col-12 mb-4 busqueda-content__titulo">
        {% if categoria %}
        <h2 class="display-4 text-center text-capitalize ">
            {{ titulo_seccion }}
            <strong>
                "{{ categoria }}"
            </strong>
        </h2>
        {% endif %}

        {% if texto_buscado %}
        <h2 class="display-4 text-center text-capitalize ">
            {{ titulo_seccion }}
            <strong>
                "{{ texto_buscado }}"
            </strong>
        </h2>
        {% endif %}
    </div>

    <!-- Productos -->
    <div class="row row-cols-1 row-cols-md-3 container justify-content-center">

        {% for producto in productos %}
            <div class="col-6 col-md-4 col-lg-3 mb-4">
                <div class="card h-100 card-img-producto-home">
                    <!-- src="https://picsum.photos/200/200?random={{ forloop.counter }}" -->
                    <img 
                    class="card-img-top mx-auto"
                    src="{{MEDIA_URL}}{{producto.imagen.url}}"
                    alt="{{producto.titulo}}"
                    >
                    <div class="card-body text-center">
                        <h4 class="card-title">{{ producto.titulo.title|truncatechars:30 }}</h4>
                        <p class="card-text ">{{ producto.descripcion.capitalize|truncatechars:50 }}</p>
                        <a href="{% url 'SITIO:producto_show' producto.id %}" class="btn btn-success btn-block">Ver</a>

                        {% if user.is_superuser %}
                            <a href="{% url 'SITIO:producto_edit' producto.id %}" class="btn btn-outline-secondary btn-block">Editar</a>
                            <a href="{% url 'SITIO:producto_delete' producto.id %}" class="btn btn-outline-danger btn-block">Eliminar</a>
                        {% endif %}
                        
                    </div>
                </div>
            </div>
        {% empty %}
        <h2 class="col-12 display-4 text-center mt-5" style="font-size: 2em; height: 30vh;">No hay productos que
            coincidan</h2>
        {% endfor %}

    </div>

</section>
{% endblock %}

sitio/templates/sitio/producto/show.html
{% extends "sitio/layout.html" %}

{% block content %}
<section class="row my-5 container">

    <!-- Titulo -->
    <!-- <div class="col-12 mb-4 ">
        <h2 class="display-4 text-center text-capitalize">{{ producto.titulo }}</h2>
    </div> -->

    <div class="col-10 mx-auto">
        <div class="row border">

            <!-- Imagen -->
            <div class="col-md-5 p-0 ">
                <!-- <img src="https://picsum.photos/id/197/400/400" alt="" class="img-fluid w-100"> -->
                <img src="{{MEDIA_URL}}{{producto.imagen.url}}" alt="{{producto.titulo}}" class="img-fluid w-100">
            </div>

            <!-- Texto -->
            <div class="col-md-7 p-4 d-flex flex-column justify-content-between">
                <div class="detalle-producto-content__text">
                    <h1 class="display-4 text-capitalize">{{ producto.titulo }}</h1>

                    <h2 class="display-4 text-capitalize mb-3">Categoria: {{ producto.categoria.descripcion }}</h2>

                    <p>{{ producto.descripcion.capitalize }}</p>
                </div>

                <div class="d-flex justify-content-between align-items-center">
                    <p class="m-0">
                        <strong>Precio:</strong>
                        ${{ producto.precio }}
                    </p>
                    <form action="{% url 'SITIO:carrito_save' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="producto_id" value="{{ producto.id }}">
                        {% if user.is_superuser or not user.is_authenticated %}
                            <button type="submit" class="btn btn-success" disabled>Agregar al carrito</button>
                        {% else %}
                            <button type="submit" class="btn btn-success">Agregar al carrito</button>
                        {% endif %}
                    </form>
                </div>
            </div>

        </div>
    </div>

</section>
{% endblock %}